In [5]:
# para se trabalhar com a biblioteca numpy, precisamos realizar a sua importação

In [1]:
import numpy as np

In [ ]:
# Criando um array
# Diferentemente das listas Python, os arrays numpy precisam ser criados antes de serem usados. A função append(), muito útli para a criação de listas em tempo
# de execução, não existe no pacote NumPy. Para isso é necessária a utilização de funções que permitem a criação de arrays/Listas de várias maneiras.
# A maneira mais simples é através da função np.array(lista/tupla). O tamanho e/ou as dimensões de matrizes devem ser informadas no momento da criação.
# Pesquise as diferentes formas de criação de arrays NumPy

In [ ]:
# 1) matriz vazia (empty) - utiliza-se a função.np.empty(dimensões/tamanho)
# 2) matriz incializada com zeros: utiliza-se a função. np.zeros(dimensões/tamanho)
# 3) matriz inicializada com o valor 1: utiliza-se a função. np.ones(dimensões/tamanho)
# 4) com x elementos de um valor inicial até final: utiliza-se a função. np.array(Range(tamanho ou intervalo)) ou np.arange([inicio],fim,[tamanho intervalo])
# 5) matriz inicializada com valores booleanos. np.ones (tamanho,dtype=bool) ou np.full(dimensão,preenchimento,dtype=bool)
# 6) matriz inicializada com valores dentro de um intervalo, distribuídos uniformemente. np.linspace(inicio,fim,tamanho intervalo)
# 7) matriz identidade: matriz quadrada inicializada com zeros exceto na diagonal formada por 1’s. np.identity(ordem da matriz).
# 8) Matriz eye: cria uma matriz identidade bidimensional. np.eye(linhas, colunas)
# 9) matriz full: Cria uma matriz com valor de preenchimento dado. np.full(dimensão, valorpreenchimento)

In [2]:
# Criando um array vazio: Utilizando o np.empty
array = np.empty(10)
print(array)

[0.00000000e+000 3.45845952e-323 6.95046708e-310 4.94065646e-324
 5.21501687e-310 2.47032823e-323 1.42304404e+016 6.95046466e-310
 2.17124729e-314 0.00000000e+000]


In [8]:
# Exemplo de iteração usando o Array com a estrtura for

flamengo = np.array([2,4,6,3,2,3,2,5,1,4,2,0,1,0,3,2,0,2,1,0,2,2,4,1,0,1,1,2,1,4,1,1,1,2,1,1,1,3,0,
                     0,0,4,0,1,1,4,1,2,3,0,3,2,2,0,2,2,2,0,2,1,1,1,2,2,1,1,2,1,1,2,1,1,3,1,0,1,0,0,
                     0,5,2,2,2,2,1,2,2,1,3,4,2,2,0,1,1,1,1,1,1,1,2,2,3,0,0,6,0,7,2,1,2,1,5,2,1,1,2,
                     1,3,1,1,1,2,2,5,4,1,1,1,2,1,5,1,0,0,2,3,3,1,2,2,2,0,5,0,0,3,1,1,6,2,1,1,4,1,1,
                     1,1,2,1,2,0,0,2,1,3,0,3,0,4,1,1,1,2,0,0,1,0,3,1,0,0,2,0,2,4,3,2,1,2,1,1,2,3,4,
                     4,1,2,0,0,2,2,0,1,1,1,0,0,1,0,1,0,1,0,0,1,5,0,0,2,0,2,0,0,2,1,0,0,1,0,2,0,1,2,
                     2,0,4,0,1,1,0,3,2,1,2,1,1,0,0,4,2,1,1,2,1,0,2,1,2,1,1,3,3,0,0,2,0,1,1,0,0,1,0,
                     1,1,4,1,0,0,0,1,1,0,0,0,0,1,4,1,5,1,0,2,2,2,1,0,1,4,1,1,2,0,1,3,1,2,1,2,3,0,0,
                     0,1,3,2,0,2,2,1,3,1,2,0,2,2,0,2,0,5,1,0,1,2,3,1,1,2,0,0,1,2,1,5,0,1,0,4,1,4,3,
                     1,1,2,1,0,2,2,0,4,1,1,0,1,1,2,1,1,0,0,1,2,5,1,3,0,1,1,3,2,0,0,3,3,1,0,0,1,3,2,
                     3,2,0,1,2,3,1,1,2,2,1,1,3,0,1,2,3,0,3,2,1,0,2,0,3,1,2,1,2,1,0,1,3,0,1,0,0,1,2])

fluminense = np.array([3,0,3,0,0,2,1,0,1,1,2,0,3,2,3,2,3,2,3,4,1,2,3,1,1,1,1,2,1,2,3,1,1,0,0,1,4,2,
                       1,1,1,2,2,2,0,0,1,1,1,2,1,2,3,2,0,1,1,0,2,3,2,2,2,2,1,0,0,2,1,2,4,1,4,4,1,1,
                       1,3,2,2,2,1,1,1,2,1,3,1,1,1,4,2,0,2,0,1,1,5,0,3,0,2,1,1,0,1,4,0,1,1,3,3,2,5,
                       1,4,1,1,3,1,1,1,1,5,0,0,1,2,1,1,2,2,2,1,1,3,0,1,1,3,1,1,1,2,0,3,3,3,2,1,3,0,
                       0,1,2,3,2,0,1,3,0,0,2,1,1,1,2,4,0,1,0,0,0,0,0,0,1,1,3,0,0,0,2,0,1,1,2,2,3,0
                       ,1,1,1,1,1,2,0,1,1,0,3,1,0,4,0,1,2,2,1,0,1,2,3,1,0,4,2,1,0,1,1,1,0,1,4,2,0,
                       0,2,0,1,0,1,1,1,3,1,0,1,1,1,1,0,2,0,2,0,0,2,0,1,1,1,1,0,3,0,1,2,2,1,1,0,1,0,
                       1,1,0,2,1,0,1,0,1,1,1,0,0,1,0,1,0,1,1,0,0,0,0,0,0,1,1,1,1,1,2,0,1,2,1,2,1,1,
                       2,2,1,3,1,4,1,2,3,0,3,4,3,0,1,2,0,1,1,3,2,1,1,0,2,0,3,1,2,0,1,2,1,1,0,1,0,2,
                       1,4,2,3,1,4,1,0,3,2,2,2,2,4,0,2,2,1,1,2,0,2,4,0,2,1,0,0,0,1,0,3,2,3,0,1,0,2,
                       0,1,1,1,2,0,3,2,1,0,3,1,1,0,2,1,3,1,0,1,2,1,0,3,4,1,0,0,1,2,1,1,0,0,1,2,1,1,
                       0,1,2,1,1,1,1,3,1,2,1,1])

# se temos que perorrer cada elemento do array, temos que comparar cada valor na posicao i de um, com o outro

pt_fla = 0
pt_flu = 0
for i in range(len(fluminense)):
    if flamengo[i] > fluminense[i]:
        pt_fla = pt_fla + 3     # cada vitoria sao 3 pontos
    elif flamengo[i] < fluminense[i]:
        pt_flu = pt_flu + 3
    else:
        pt_flu = pt_flu + 1
        pt_fla = pt_fla + 1
print(f"Flamengo e Fluminense fizeram {len(fluminense)} jogos ")   # poderia ser len de fla
print(f"Flamengo somou {pt_fla} pontos enquanto que o fluminense somou {pt_flu}")
SomaGolsFla = sum(flamengo)
SomaGolsFlu = sum(fluminense)
print(f"Flamengo fez {SomaGolsFla} gols enquanti que o fluminense fez {SomaGolsFlu}")

Flamengo e Fluminense fizeram 429 jogos 
Flamengo somou 611 pontos enquanto que o fluminense somou 539
Flamengo fez 630 gols enquanti que o fluminense fez 571


In [ ]:
# Exemplo de iteração usando o Array sem a necessidade do for (nesse caso, estamos de fato usando o poder do numpuy)

In [ ]:
real = np.array([2,4,6,3,2,3,2,5,1,4,2,0,1,0,3,2,0,2,1,0,2,2,4,1,0,1,1,2,1,4,1,1,1,2,1,1,1,3,0,
                     0,0,4,0,1,1,4,1,2,3,0,3,2,2,0,2,2,2,0,2,1,1,1,2,2,1,1,2,1,1,2,1,1,3,1,0,1,0,0,
                     0,5,2,2,2,2,1,2,2,1,3,4,2,2,0,1,1,1,1,1,1,1,2,2,3,0,0,6,0,7,2,1,2,1,5,2,1,1,2,
                     1,3,1,1,1,2,2,5,4,1,1,1,2,1,5,1,0,0,2,3,3,1,2,2,2,0,5,0,0,3,1,1,6,2,1,1,4,1,1,
                     1,1,2,1,2,0,0,2,1,3,0,3,0,4,1,1,1,2,0,0,1,0,3,1,0,0,2,0,2,4,3,2,1,2,1,1,2,3,4,
                     4,1,2,0,0,2,2,0,1,1,1,0,0,1,0,1,0,1,0,0,1,5,0,0,2,0,2,0,0,2,1,0,0,1,0,2,0,1,2,
                     2,0,4,0,1,1,0,3,2,1,2,1,1,0,0,4,2,1,1,2,1,0,2,1,2,1,1,3,3,0,0,2,0,1,1,0,0,1,0,
                     1,1,4,1,0,0,0,1,1,0,0,0,0,1,4,1,5,1,0,2,2,2,1,0,1,4,1,1,2,0,1,3,1,2,1,2,3,0,0,
                     0,1,3,2,0,2,2,1,3,1,2,0,2,2,0,2,0,5,1,0,1,2,3,1,1,2,0,0,1,2,1,5,0,1,0,4,1,4,3,
                     1,1,2,1,0,2,2,0,4,1,1,0,1,1,2,1,1,0,0,1,2,5,1,3,0,1,1,3,2,0,0,3,3,1,0,0,1,3,2,
                     3,2,0,1,2,3,1,1,2,2,1,1,3,0,1,2,3,0,3,2,1,0,2,0,3,1,2,1,2,1,0,1,3,0,1,0,0,1,2])

barcelona = np.array([3,0,3,0,0,2,1,0,1,1,2,0,3,2,3,2,3,2,3,4,1,2,3,1,1,1,1,2,1,2,3,1,1,0,0,1,4,2,
                       1,1,1,2,2,2,0,0,1,1,1,2,1,2,3,2,0,1,1,0,2,3,2,2,2,2,1,0,0,2,1,2,4,1,4,4,1,1,
                       1,3,2,2,2,1,1,1,2,1,3,1,1,1,4,2,0,2,0,1,1,5,0,3,0,2,1,1,0,1,4,0,1,1,3,3,2,5,
                       1,4,1,1,3,1,1,1,1,5,0,0,1,2,1,1,2,2,2,1,1,3,0,1,1,3,1,1,1,2,0,3,3,3,2,1,3,0,
                       0,1,2,3,2,0,1,3,0,0,2,1,1,1,2,4,0,1,0,0,0,0,0,0,1,1,3,0,0,0,2,0,1,1,2,2,3,0
                       ,1,1,1,1,1,2,0,1,1,0,3,1,0,4,0,1,2,2,1,0,1,2,3,1,0,4,2,1,0,1,1,1,0,1,4,2,0,
                       0,2,0,1,0,1,1,1,3,1,0,1,1,1,1,0,2,0,2,0,0,2,0,1,1,1,1,0,3,0,1,2,2,1,1,0,1,0,
                       1,1,0,2,1,0,1,0,1,1,1,0,0,1,0,1,0,1,1,0,0,0,0,0,0,1,1,1,1,1,2,0,1,2,1,2,1,1,
                       2,2,1,3,1,4,1,2,3,0,3,4,3,0,1,2,0,1,1,3,2,1,1,0,2,0,3,1,2,0,1,2,1,1,0,1,0,2,
                       1,4,2,3,1,4,1,0,3,2,2,2,2,4,0,2,2,1,1,2,0,2,4,0,2,1,0,0,0,1,0,3,2,3,0,1,0,2,
                       0,1,1,1,2,0,3,2,1,0,3,1,1,0,2,1,3,1,0,1,2,1,0,3,4,1,0,0,1,2,1,1,0,0,1,2,1,1,
                       0,1,2,1,1,1,1,3,1,2,1,1])

# Observe que acima, não utilizamos nenhum conceito de numpy, exceto o array.
# O objetivo do arrray é de fato podermos iterar sobre os elementos sem usar o for.

saldo_gols = real - barcelona

empates = len(saldo_gols[saldo_gols == 0])
vitorias_real = len(saldo_gols[saldo_gols > 0])
vitorias_barca = len(saldo_gols[saldo_gols < 0])

pontos_real = empates + 3 * vitorias_real
pontos_barca = empates + 3 * vitorias_barca

print("Empates:", empates)
print("Real: vitórias", vitorias_real, "pontos", pontos_real)
print("Barcelona: vitórias", vitorias_barca, "pontos", pontos_barca)

In [ ]:
# se quisermos criar um contador, nao podemos usar o empty
# para percorrermos celula a celula dentro de uma matriz, precisamos de for dentro do for
# unidimencional, temos 1 for, bidimencional temos 2 for, tridimencional temos 3 for, sempre um for dentro do outro

In [9]:
# Criando uma matriz vazia com 3 linhas e 4 colunas

matriz = np.zeros([3,4])
print(matriz)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
# Criando uma matriz de 3 linhas e 4 colunas usando a função ones. A função ones coloca 1 em todas as linhas
matriz = np.ones([3,4])
print(matriz)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
# Criando uma matriz de 5 linhas e 5 colunas, usando o eye.Essa funcao eye, coloca os valores 1 na diagonal
matriz = np.eye(5,5)
print(matriz)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
# A função diag retorna os valores na diagonal em uma matriz
mat = np.array([[1,2,3,4],
                [5,6,7,8],
                [8,7,6,5],
                [4,3,2,1]])
diag = np.diag(mat)
print(diag)

[1 6 6 1]


In [14]:
# Matriz unidimencional
z = np.array([1,2,3,4,5,6,7,8])
print(z)
# a funcao shape retorna o numero de linhas(que é o numero de elementos) da matriz
print("vetor1D= ",z.shape)


z = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
print("vetor2D= ",z.shape)
# a funcao shape retorna o numero de linhas(que é o numero de elementos) da minha matriz
# a funcao array retorna uma tupla
for i in range(z.shape[0]):
    for j in range(z.shape[1]):
        print(z[i,j])

[1 2 3 4 5 6 7 8]
vetor1D=  (8,)
vetor2D=  (4, 4)
1
2
3
4
2
3
4
5
3
4
5
6
4
5
6
7


In [3]:
# substituir os valores ímpares da matriz por -1, percorrendo a matriz elemento a elemento
mat = np.array([[1,2,3,4],
                [5,6,7,8],
                [8,7,6,5],
                [4,3,2,1]])

for i in range(mat.shape[0]):
    for j in range(mat.shape[1]):
        if mat[i,j] % 2 != 0:
            mat[i,j] = -1
print(mat)


# quando ela é bidimencional, nao podemos usar o len, apenas o shape, para linha e coluna

[[-1  2 -1  4]
 [-1  6 -1  8]
 [ 8 -1  6 -1]
 [ 4 -1  2 -1]]


In [6]:
# usando os elementos gerados anteriormente, temos que somar os elementos da diagonal sem usar o for e o diag
soma = 0

for i in range(mat.shape[0]):
    for j in range(mat.shape[1]):
        if i == j:
            soma = soma + mat[i,j]
print(soma)

 O Predisdente Michel Temer foi o mais velho a assumir a presidencia 75 anos
 O Predisdente Fernando Collor foi o mais novo a assumir a presidencia 40 anos


In [ ]:
# Fatiamento de array, quando é unidimencional é igual a lista
arr = np.arange(10, 34, 2) # Cria o array arr iniciando em 10 incrementando de 2 unidades até o 34
print(arr)
# observe que o passo é de 2 em 2 e ele termina em 32

In [ ]:
arr[:4] # os primeiros quatro elmentos

In [ ]:
arr[5:] # exibe a partir do 6º elemento (índice = 5) até o final

In [ ]:
arr[1::2] # exibe os elementos espaçados de 2 em 2 posições, a partir da  posição 2 até o fim do array

In [ ]:
arr[::-1]  # exibe todos os elementos na ordem inversa

In [ ]:
arr[5::-2]  # exibe os elementos a partir do índice 5, de -2 em -2,até

In [ ]:
arr = arr.reshape((4,3)) #Redimensiona o array para 4 linhas x 3 colunas

In [ ]:
arr[:2,:2] # exibe o array com 2 linhas e 2 colunas

In [ ]:
arr[:-1,:-1] #Exibe da 1 linha até a penúltima e da 1 coluna até a penúltima